name: "Deploy to .org & upload artifact(s)"

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run composer install
        run: |
          composer install --no-interaction

      - name: Run composer update with --no-dev
        run: |
          composer update --no-dev --no-interaction --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          npm install --omit=dev

#      - name: WordPress Plugin Deploy
#        if: |
#          github.event_name == 'release' && !github.event.release.prerelease
#        uses: 10up/action-wordpress-plugin-deploy@stable
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
#          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
#          SLUG: custom-login

      - name: Create Artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/custom-login"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-login
          path: plugin-build/custom-login.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: plugin-build/custom-login.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
