name: "Downgrade to PHP 7.4"

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  tag:
    name: Downgrade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cp -f composer-php-74.json composer.json

      - name: Run composer install
        run: |
          composer install --no-interaction

      - name: Run Rector
        run: vendor/bin/rector --debug --ansi

      - name: Remove Rector & dump autoloader
        run: |
          composer remove --no-update rector/rector 
          composer dump

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          npm install --omit=dev

      - run: mkdir plugin-build

      - name: Create Artifact
        run: |
          composer archive --format="zip" --file="plugin-build/custom-login-php74"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-login-php74
          path: plugin-build/

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: plugin-build/custom-login-php74.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
