name: "Temp PR Downgrade Test"

on:
  pull_request:
    branches:
      - 'feature/rector**'
  workflow_dispatch:

jobs:
  tag:
    name: Downgrade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run composer install
        run: |
          composer install --no-interaction

      - name: Update composer PHP 7.4
        run: |
          composer config platform.php 7.4
          composer require --no-update php:~7.4

      - name: Run rector downgrade
        run: vendor/bin/rector process

      - name: Run composer update with --no-dev
        run: |
          composer config platform.php 8.3
          composer require --no-update php:^8.3
          composer update --no-dev --no-interaction --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          npm install --omit=dev

      - run: mkdir plugin-build

      - name: Create Artifact
        run: |
          composer archive --format="zip" --file="plugin-build/custom-login-php74"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-login-php74
          path: plugin-build/
